import type { Skill } from "@/lib/skill";

/** Fallback offline (sin DATABASE_URL). Misma lista que sql/005_skills.sql. */
export const defaultSkills: Skill[] = [
  // Frontend
  { id: "d-react", name: "React", category: "frontend", iconUrl: "https://cdn.simpleicons.org/react/61DAFB", iconKey: "react", sortOrder: 0 },
  { id: "d-rn", name: "React Native", category: "frontend", iconUrl: "https://cdn.simpleicons.org/react/61DAFB", iconKey: "react-native", sortOrder: 1 },
  { id: "d-next", name: "Next.js", category: "frontend", iconUrl: "https://cdn.simpleicons.org/nextdotjs/ffffff", iconKey: "nextdotjs", sortOrder: 2 },
  { id: "d-js", name: "JavaScript", category: "frontend", iconUrl: "https://cdn.simpleicons.org/javascript/F7DF1E", iconKey: "javascript", sortOrder: 3 },
  { id: "d-ts", name: "TypeScript", category: "frontend", iconUrl: "https://cdn.simpleicons.org/typescript/3178C6", iconKey: "typescript", sortOrder: 4 },
  { id: "d-html", name: "HTML5", category: "frontend", iconUrl: "https://cdn.simpleicons.org/html5/E34F26", iconKey: "html5", sortOrder: 5 },
  { id: "d-css", name: "CSS3", category: "frontend", iconUrl: "https://cdn.simpleicons.org/css3/1572B6", iconKey: "css3", sortOrder: 6 },
  { id: "d-tw", name: "Tailwind CSS", category: "frontend", iconUrl: "https://cdn.simpleicons.org/tailwindcss/06B6D4", iconKey: "tailwindcss", sortOrder: 7 },
  { id: "d-zod", name: "Zod", category: "frontend", iconUrl: "https://cdn.simpleicons.org/zod/3E67B1", iconKey: "zod", sortOrder: 8 },
  { id: "d-zt", name: "Zustand", category: "frontend", iconUrl: "https://repository-images.githubusercontent.com/180328715/fca49300-e7f1-11ea-9f51-cfd949b31560", iconKey: "zustand", sortOrder: 9 },
  { id: "d-bs", name: "Bootstrap", category: "frontend", iconUrl: "https://cdn.simpleicons.org/bootstrap/7952B3", iconKey: "bootstrap", sortOrder: 10 },
  { id: "d-rd", name: "Responsive Design", category: "frontend", iconUrl: "https://cdn.simpleicons.org/materialdesign/ffffff", iconKey: "responsive-design", sortOrder: 11 },
  { id: "d-expo", name: "Expo", category: "frontend", iconUrl: "https://cdn.simpleicons.org/expo/ffffff", iconKey: "expo", sortOrder: 12 },

  // Backend
  { id: "d-java", name: "Java", category: "backend", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg", iconKey: "java", sortOrder: 0 },
  { id: "d-spring", name: "Spring Boot", category: "backend", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg", iconKey: "spring", sortOrder: 1 },
  { id: "d-py", name: "Python", category: "backend", iconUrl: "https://cdn.simpleicons.org/python/3776AB", iconKey: "python", sortOrder: 2 },
  { id: "d-dj", name: "Django", category: "backend", iconUrl: "https://cdn.simpleicons.org/django/092E20", iconKey: "django", sortOrder: 3 },
  { id: "d-flask", name: "Flask", category: "backend", iconUrl: "https://cdn.simpleicons.org/flask/ffffff", iconKey: "flask", sortOrder: 4 },
  { id: "d-pg", name: "PostgreSQL", category: "backend", iconUrl: "https://cdn.simpleicons.org/postgresql/4169E1", iconKey: "postgresql", sortOrder: 5 },
  { id: "d-mongo", name: "MongoDB", category: "backend", iconUrl: "https://cdn.simpleicons.org/mongodb/47A248", iconKey: "mongodb", sortOrder: 6 },
  { id: "d-oracle", name: "Oracle", category: "backend", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg", iconKey: "oracle", sortOrder: 7 },
  { id: "d-mysql", name: "MySQL", category: "backend", iconUrl: "https://cdn.simpleicons.org/mysql/4479A1", iconKey: "mysql", sortOrder: 8 },
  { id: "d-mssql", name: "SQL Server", category: "backend", iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg", iconKey: "sqlserver", sortOrder: 9 },
  { id: "d-fb", name: "Firebase", category: "backend", iconUrl: "https://cdn.simpleicons.org/firebase/FFCA28", iconKey: "firebase", sortOrder: 10 },
  { id: "d-node", name: "Node.js", category: "backend", iconUrl: "https://cdn.simpleicons.org/nodedotjs/339933", iconKey: "nodedotjs", sortOrder: 11 },
  { id: "d-auth0", name: "Auth0", category: "backend", iconUrl: "https://cdn.simpleicons.org/auth0/EB5424", iconKey: "auth0", sortOrder: 12 },
  { id: "d-jwt", name: "JWT", category: "backend", iconUrl: "https://cdn.simpleicons.org/jsonwebtokens/ffffff", iconKey: "jsonwebtokens", sortOrder: 13 },

  // DevOps
  { id: "d-docker", name: "Docker", category: "devops", iconUrl: "https://cdn.simpleicons.org/docker/2496ED", iconKey: "docker", sortOrder: 0 },
  { id: "d-k8s", name: "Kubernetes", category: "devops", iconUrl: "https://cdn.simpleicons.org/kubernetes/326CE5", iconKey: "kubernetes", sortOrder: 1 },
  { id: "d-gcp", name: "GCP", category: "devops", iconUrl: "https://cdn.simpleicons.org/googlecloud/4285F4", iconKey: "googlecloud", sortOrder: 2 },
  { id: "d-gha", name: "GitHub Actions", category: "devops", iconUrl: "https://cdn.simpleicons.org/githubactions/2088FF", iconKey: "githubactions", sortOrder: 3 },
  { id: "d-cicd", name: "CI/CD", category: "devops", iconUrl: "https://cdn.simpleicons.org/gitlab/FCA121", iconKey: "cicd", sortOrder: 4 },

  // Other
  { id: "d-git", name: "Git", category: "other", iconUrl: "https://cdn.simpleicons.org/git/F05032", iconKey: "git", sortOrder: 0 },
  { id: "d-agile", name: "Agile/Scrum", category: "other", iconUrl: "https://cdn.simpleicons.org/jira/0052CC", iconKey: "agile-scrum", sortOrder: 1 },
  { id: "d-rup", name: "RUP", category: "other", iconUrl: "https://cdn.simpleicons.org/uml/008000", iconKey: "rup", sortOrder: 2 },
  { id: "d-uml", name: "Diagramas UML", category: "other", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/UML_logo.svg", iconKey: "uml", sortOrder: 3 },
  { id: "d-linux", name: "Linux", category: "other", iconUrl: "https://cdn.simpleicons.org/linux/FCC624", iconKey: "linux", sortOrder: 4 },
  { id: "d-postman", name: "Postman", category: "other", iconUrl: "https://cdn.simpleicons.org/postman/FF6C37", iconKey: "postman", sortOrder: 5 },
  { id: "d-dsa", name: "DSA", category: "other", iconUrl: "https://cdn.simpleicons.org/leetcode/FFA116", iconKey: "dsa", sortOrder: 6 },
  { id: "d-ct", name: "Critical Thinking", category: "other", iconUrl: "https://cdn.simpleicons.org/openai/ffffff", iconKey: "critical-thinking", sortOrder: 7 },
  { id: "d-ps", name: "Problem Solving", category: "other", iconUrl: "https://cdn.simpleicons.org/hackerrank/2EC866", iconKey: "problem-solving", sortOrder: 8 },
  { id: "d-excel", name: "Excel", category: "other", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Microsoft_Office_Excel_%282019%E2%80%932025%29.svg/826px-Microsoft_Office_Excel_%282019%E2%80%932025%29.svg.png", iconKey: "excel", sortOrder: 9 },
  { id: "d-pbi", name: "Power BI", category: "other", iconUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/New_Power_BI_Logo.svg/2048px-New_Power_BI_Logo.svg.png", iconKey: "powerbi", sortOrder: 10 },
  { id: "d-ml", name: "Machine Learning", category: "other", iconUrl: "https://cdn.simpleicons.org/tensorflow/FF6F00", iconKey: "tensorflow", sortOrder: 11 },
  { id: "d-jest", name: "Jest", category: "other", iconUrl: "https://cdn.simpleicons.org/jest/C21325", iconKey: "jest", sortOrder: 12 },
  { id: "d-ngrok", name: "Ngrok", category: "other", iconUrl: "https://cdn.simpleicons.org/ngrok/ffffff", iconKey: "ngrok", sortOrder: 13 },
  { id: "d-sd", name: "System Design", category: "other", iconUrl: "https://cdn.simpleicons.org/blueprint/ffffff", iconKey: "system-design", sortOrder: 14 },
  { id: "d-togaf", name: "TOGAF", category: "other", iconUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCuj8qdhIcMomeAgAi8QOpNvHvWztj5SLAtA&s", iconKey: "togaf", sortOrder: 15 },
  { id: "d-bizagi", name: "Bizagi", category: "other", iconUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRripaurgH1sQd_zTqPRPDuLmAUN9m8UB-wyw&s", iconKey: "bizagi", sortOrder: 16 },
  { id: "d-plantuml", name: "PlantUML", category: "other", iconUrl: "https://cdn.hashnode.com/res/hashnode/image/upload/v1609283590230/mqeCBmvO_.png", iconKey: "plantuml", sortOrder: 17 },
  { id: "d-mono", name: "Monolithic", category: "other", iconUrl: "https://cdn.simpleicons.org/microstrategy/ffffff", iconKey: "monolithic", sortOrder: 18 },
  { id: "d-micro", name: "Microservices", category: "other", iconUrl: "https://cdn.simpleicons.org/openstack/ffffff", iconKey: "microservices", sortOrder: 19 },
  { id: "d-layer", name: "Layered Arch.", category: "other", iconUrl: "https://cdn.simpleicons.org/codesandbox/ffffff", iconKey: "layered-arch", sortOrder: 20 },
];
